config/routes.rb
Rails.application.routes.draw do
  resources :categories

  devise_for :users
  resources :articles do
    resources :comments, only: [:create, :destroy, :update, :show]
  end
  root 'welcome#index'
  get "/dashboard", to: "welcome#dashboard"
  put "/articles/:id/published", to: "articles#publish"
=begin
  get "/articles"
  post "/articles"
  delete "/articles"
  get "/articles/:id"
  get "/articles/new"
  get "/articles/:id/edit"
  patch "/articles/:id"
  put "/articles/:id"
=end

end

app/views/partials/_navigation.html.erb
<header>
	<nav class="be-red white large-padding">
		<ul class="no-list row center-xs middle-xs">
			<li class="col-md">
				<h1 class="no-margin" id="logo"><%=link_to "Blog Facilito", root_path%></h1>
			</li>
			
			<li class="col-md">
				<%= link_to "Articulos", articles_path %>
			</li>
			<li>
				<% @categories.each do |category| %>
					<li class="col-md">
						<%= link_to category.name, category %>
					</li>	
				<% end %>
			</li>
			<% if user_signed_in? %>
				<% if current_user.is_admin? %>
					<li class="col-md">
						<%= link_to "Dashboard", dashboard_path %>
					</li>
				<% end %>
				
				<li class="col-md">
					<%= link_to "Cerrar Sesión", destroy_user_session_path, method: :delete %>
				</li>
			<% else %>
				<li class="col-md">
					<%= link_to "Iniciar Sesión", new_user_session_path %>
				</li>
				<li class="col-md">
					<%= link_to "Crear Cuenta", new_user_registration_path %>
				</li>
			<% end -%>
		</ul>
	</nav>
</header>